#specify language
language : generic

#Give instruction that sudo is required
sudo : required

#Specify services required
services: 
  - docker

#Specify instructions before install
before_install: 
  - docker build -t shravan2406/docker-react -f Dockerfile.dev .

#Specify what to run to build the file.
script:
  - docker run -e CI=true shravan2406/docker-react npm run test -- --watchAll=false 

#Configuration setup for deployment 
deploy: 
  provider: elasticbeanstalk
  region : "ap-south-1"
  app : "docker-react-app"
  env : "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-234479582223"
  bucket_path : "docker-react-app"
  on : 
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_KEY