#specify language
language : generic

#Give instruction that sudo is required
sudo : required

#Specify services required
services: 
  - docker

#Specify instructions before install
before_install: 
  - docker build -t shravan2406/docker-react -f Dockerfile.dev .

#Specify what to run to build the file.
script:
  - docker run -e CI=true shravan2406/docker-react npm run test -- --watchAll=false 
